### ISSUE TITLE
Fikse source map

### ISSUE THREAD

**Issue by guroseter** [ewendel/redux-workshop#23]
Flere slet med debugging under workshoppen, kanskje vi kunne få til source map så det hadde blitt enklere å finne frem til riktig kodelinje

**Comment by ingara** [comment]
Innbiller meg at det bør funke hvis vi bytter til `cheap-module-source-map`.

**Comment by ingara** [comment]
Fikset av https://github.com/ewendel/redux-workshop/commit/1d6eaacfea91364262868370619074da66d7468e.
